version: '3.7'

services:
  web:
    build: 
      context: ./donation
      dockerfile: Dockerfile
    volumes:
      - ./donation:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./donation/.env
    command: sh scripts/run_server.sh
    depends_on: 
      - database
    
  database:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: