# Generated by Django 2.1.1 on 2019-07-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Call',
        ),
    ]
