# Generated by Django 2.1.1 on 2019-04-18 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_resetpasswordcode'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
