# Generated by Django 2.1.1 on 2019-04-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='title',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='package',
            name='body',
        ),
        migrations.AddField(
            model_name='package',
            name='content_type',
            field=models.CharField(choices=[('0', 'Food'), ('1', 'Clothes'), ('2', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
