# Generated by Django 2.1.1 on 2019-04-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20190419_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='to_address',
        ),
        migrations.RemoveField(
            model_name='package',
            name='to_wilaya',
        ),
    ]
