# Generated by Django 2.1.1 on 2019-07-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20190506_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='largitude',
        ),
        migrations.RemoveField(
            model_name='package',
            name='longitude',
        ),
    ]
